---
- name: restart tomcat 
  service: 
    name: tomcat 
    state: restarted 
  listen: deploy war

- name: back up ROOT
  shell: mv /opt/tomcat/latest/webapps/ROOT /opt/tomcat/latest/webapps/ROOT_backup
  listen: deploy war
  register: deploywar

- name: copy war file to tomcat webapps 
  copy: 
    src: Bookstore0.0.8.war
    dest: /opt/tomcat/latest/webapps/ROOT.war
  listen: deploy war

