- name: Create database user with name 'dbadmin' and password 'dbpassword' with all database privileges
  mysql_user:
    name: dbadmin
    password: dbpassword
    priv: '*.*:ALL'
    state: present
    host: '%'
- mysql_db:
    name: Bookstore
    state: present
  notify: add table

