- name: Create database user with all database privileges
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
- name: create database Bookstore 
  mysql_db:
    name: Bookstore
    state: present
  notify: add table

