- hosts: loadbalancer
  become: yes 
  tasks: 

    -  name: copy conf to loadbalancer 
       template: 
         src: app.conf.j2
         dest: /etc/nginx/conf.d/app.conf
       notify: nginx restart 
   
  handlers: 
     
    - name: nginx restart 
      become: yes
      service: 
        name: nginx 
        state: restarted 
       
