version: "3.3" 

services: 

  app1:
    container_name: app1 
    build: .
    hostname: app1 
    privileged: true 
    ports: 
     - "8081:8080"
    restart: unless-stopped 
    networks:
      my_net: 
        ipv4_address: 10.0.0.2 

  app2:
    container_name: app2
    build: .
    hostname: app2
    privileged: true
    ports: 
     - "8082:8080"
    restart: unless-stopped
    networks: 
      my_net:
        ipv4_address: 10.0.0.3

  lb:
    container_name: lb
    build: .
    hostname: lb
    privileged: true
    ports: 
     - "8083:8888"
    restart: unless-stopped
    networks: 
      my_net:
        ipv4_address: 10.0.0.4      

  db:
    container_name: db
    build: .
    hostname: db
    privileged: true
    restart: unless-stopped
    networks: 
      my_net:
        ipv4_address: 10.0.0.5

  js1:
    container_name: js1
    build: .
    hostname: js1
    privileged: true
    restart: unless-stopped
    networks: 
      my_net:  
        ipv4_address: 10.0.0.6

  js2: 
    container_name: js2
    build: .
    hostname: js2
    privileged: true
    restart: unless-stopped
    networks: 
      my_net: 
        ipv4_address: 10.0.0.7

networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.1/24"        
