---
- name: install epel-release
  dnf:
    name: epel-release
    state: present

- name: install ngnix at loadbalancer
  dnf:
    name: nginx
    state: present

- name: make sure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: copy conf to loadbalancer
  copy:
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf
  notify: nginx restart
